/// Business Types for Zambian Businesses
class BusinessTypes {
  static const List<String> types = [
    'Retail Shop',
    'Supermarket',
    'Grocery Store',
    'Restaurant',
    'Fast Food',
    'Cafe/Coffee Shop',
    'Bar/Pub',
    'Hotel',
    'Guest House',
    'Pharmacy',
    'Clinic/Medical Center',
    'Hospital',
    'Salon/Barbershop',
    'Spa/Beauty Center',
    'Gym/Fitness Center',
    'Electronics Store',
    'Clothing/Fashion Store',
    'Shoe Store',
    'Hardware Store',
    'Auto Parts Shop',
    'Fuel Station',
    'Car Wash',
    'Bakery',
    'Butchery',
    'Fish Market',
    'Vegetable Market',
    'Wholesale',
    'Warehouse',
    'Manufacturing',
    'Printing/Stationery',
    'Bookshop',
    'Mobile Money Agent',
    'Phone/Airtime Shop',
    'Internet Cafe',
    'Laundry Service',
    'Tailoring/Fashion Design',
    'Carpentry/Furniture',
    'Plumbing Services',
    'Electrical Services',
    'Construction Services',
    'Real Estate Agency',
    'Car Rental',
    'Transport/Logistics',
    'Travel Agency',
    'Photography Studio',
    'Event Planning',
    'Catering Services',
    'Agricultural Supplier',
    'Veterinary Services',
    'Pet Shop',
    'Daycare/Nursery',
    'School/Training Center',
    'Other',
  ];

  static String get defaultType => 'Retail Shop';
}
