/// Zambian Provinces and Districts
class ZambiaLocations {
  static const String country = 'Zambia';

  static const Map<String, List<String>> provincesAndDistricts = {
    'Central Province': [
      'Kabwe',
      'Kapiri Mposhi',
      'Mkushi',
      'Serenje',
      'Mumbwa',
      'Chibombo',
      'Ngabwe',
      'Luano',
      'Chitambo',
      'Shibuyunji',
    ],
    'Copperbelt Province': [
      'Ndola',
      'Kitwe',
      'Chingola',
      'Mufulira',
      'Luanshya',
      'Kalulushi',
      'Chilibombwe',
      'Lufwanyama',
      'Masaiti',
      'Mpongwe',
    ],
    'Eastern Province': [
      'Chipata',
      'Katete',
      'Petauke',
      'Lundazi',
      'Chama',
      'Chadiza',
      'Nyimba',
      'Sinda',
      'Vubwi',
      'Mambwe',
    ],
    'Luapula Province': [
      'Mansa',
      'Nchelenge',
      'Kawambwa',
      'Samfya',
      'Mwense',
      'Milenge',
      'Chembe',
      'Chienge',
      'Lunga',
      'Chipili',
    ],
    'Lusaka Province': [
      'Lusaka',
      'Kafue',
      'Chilanga',
      'Chongwe',
      'Luangwa',
      'Rufunsa',
      'Chirundu',
    ],
    'Muchinga Province': [
      'Chinsali',
      'Isoka',
      'Mpika',
      'Nakonde',
      'Shiwang\'andu',
      'Lavushimanda',
      'Kanchibiya',
      'Mafinga',
    ],
    'Northern Province': [
      'Kasama',
      'Mbala',
      'Luwingu',
      'Mporokoso',
      'Kaputa',
      'Nsama',
      'Lupososhi',
      'Lunte',
      'Senga Hill',
    ],
    'North-Western Province': [
      'Solwezi',
      'Kasempa',
      'Mwinilunga',
      'Zambezi',
      'Kabompo',
      'Chavuma',
      'Kalumbila',
      'Ikelenge',
      'Mufumbwe',
    ],
    'Southern Province': [
      'Livingstone',
      'Choma',
      'Monze',
      'Kalomo',
      'Mazabuka',
      'Namwala',
      'Siavonga',
      'Kazungula',
      'Zimba',
      'Chirundu',
      'Pemba',
      'Sinazongwe',
      'Gwembe',
      'Itezhi-Tezhi',
    ],
    'Western Province': [
      'Mongu',
      'Kaoma',
      'Senanga',
      'Sesheke',
      'Lukulu',
      'Kalabo',
      'Shangombo',
      'Nalolo',
      'Luampa',
      'Sioma',
      'Mitete',
      'Nkeyema',
      'Sikongo',
      'Limulunga',
    ],
  };

  static List<String> get provinces => provincesAndDistricts.keys.toList();

  static List<String> getDistricts(String province) {
    return provincesAndDistricts[province] ?? [];
  }
}
