// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBltgtGrrg2EiHlVa9yd-FKCOYXdopCfro',
    appId: '1:665660132240:web:4e61a81699ee2ccd320115',
    messagingSenderId: '665660132240',
    projectId: 'dynamos-pos',
    authDomain: 'dynamos-pos.firebaseapp.com',
    storageBucket: 'dynamos-pos.firebasestorage.app',
    measurementId: 'G-4W1PYZE32N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBltgtGrrg2EiHlVa9yd-FKCOYXdopCfro',
    appId: '1:665660132240:android:4e61a81699ee2ccd320115',
    messagingSenderId: '665660132240',
    projectId: 'dynamos-pos',
    storageBucket: 'dynamos-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBltgtGrrg2EiHlVa9yd-FKCOYXdopCfro',
    appId: '1:665660132240:ios:4e61a81699ee2ccd320115',
    messagingSenderId: '665660132240',
    projectId: 'dynamos-pos',
    storageBucket: 'dynamos-pos.firebasestorage.app',
    iosBundleId: 'com.kalootechnologies.dynamospos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBltgtGrrg2EiHlVa9yd-FKCOYXdopCfro',
    appId: '1:665660132240:ios:4e61a81699ee2ccd320115',
    messagingSenderId: '665660132240',
    projectId: 'dynamos-pos',
    storageBucket: 'dynamos-pos.firebasestorage.app',
    iosBundleId: 'com.kalootechnologies.dynamospos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBltgtGrrg2EiHlVa9yd-FKCOYXdopCfro',
    appId: '1:665660132240:web:4e61a81699ee2ccd320115',
    messagingSenderId: '665660132240',
    projectId: 'dynamos-pos',
    authDomain: 'dynamos-pos.firebaseapp.com',
    storageBucket: 'dynamos-pos.firebasestorage.app',
    measurementId: 'G-4W1PYZE32N',
  );
}
